- name: install nginx
  yum: name=nginx
  tags: nginx

#- name: install nginx
#  command: amazon-linux-extras install nginx1.12
#  tags: nginx

- file: path=/etc/sysconfig/network state=touch follow=yes
  tags: nginx

#- name: copy nginx.conf
#  template: src=nginx.conf.j2 dest=/etc/nginx/nginx.conf
#  tags: nginx

#- name: copy libra.conf
#  template: src=libra.conf.j2 dest=/etc/nginx/conf.d/libra.conf mode=0755
#  tags: nginx

- name: restart nginx
  service: name=nginx state=restarted
  tags: nginx
